[package]
name = "nethack-data"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
nethack-types.workspace = true
thiserror.workspace = true
winnow.workspace = true

[dev-dependencies]
strum.workspace = true
